### ISSUE TITLE
Install theme?

### ISSUE THREAD

**Issue by apreshill** [r-lib/hugodown#25]
Will hugodown have functions to install a theme from GitHub? Or is it mainly focused on existing Hugo/blogdown sites? If intended as a full Hugo site tool, I appreciated this feature in blogdown:
https://github.com/rstudio/blogdown/issues/391

**Comment by maelle** [comment]
Adding a question to the thread. If theme installation gets supported, then how, modules or theme= or both? "Modules" seem to be the future.  

https://gohugo.io/hugo-modules/use-modules/#use-a-module-for-a-theme

https://discourse.gohugo.io/t/hugo-modules-for-dummies/20758/3 (h/t https://blog.jemu.name/2020/05/hugo-theme-components-modules/)

**Comment by hadley** [comment]
I have a been thinking about a couple of functions for specific themes (eg academic and something else). There’s so much diversity in themes that it’s going to be very hard to deliver a convenient experience in general, so I’d rather focus on building out one or two themes to help get people up and running as quickly as possible. (And then more experienced Hugo + R users could contribute code for other themes based on those functions)

**Comment by maelle** [comment]
it'd be like distill! :clap: 

Just wanted to note that when using modules and not vendoring the modules, @apreshill there's no themes folder to mess with, which you might like :wink: (there might be downsides to not vendoring of course)

**Comment by hadley** [comment]
I think having a static themes folder that you control precisely when is updated is likely to be the safest strategy. I’d prefer to avoid modules as they look like an additional layer of complexity.

**Comment by maelle** [comment]
Right. Especially that one needs Go, that's a big problem (if modules didn't have these problems, I'd vaguely suggest a setup recommending a theme module with version number, like a release of the theme, + vendoring in an app dir by hugodown).

**Comment by hadley** [comment]
(not that it matters, but the way I'm installing hugo should now avoid any issues of that sort)

**Comment by maelle** [comment]
(which issues? sorry)

**Comment by hadley** [comment]
(the needing of go; hugodown installs a hugo binary so you don't need any other external dependencies)

**Comment by maelle** [comment]
(I was referring to https://gohugo.io/hugo-modules/use-modules/#prerequisite <- as far as I understood, to use modules you need Hugo _and a newer version of Go, plus a version control system_, but I might have gotten that wrong, and it might change)

**Comment by hadley** [comment]
(right, that's what I was meaning that you don't need to worry about 😄)

**Comment by maelle** [comment]
(even Go?! I'll read more then. And think modules are good in that case since one would really declare the dependency on a version of a theme :-) )

**Comment by hadley** [comment]
(yes, I'd say that go is an external dependency)

**Comment by hadley** [comment]
Notes to self on what creating a hugo academic site entails

* [Pin to 4.8](https://sourcethemes.com/academic/updates/v4.8.0/), since changes to theme may break hacks or require newer version of hugo
* Install hugo 0.66.0 (extended)
* Download https://github.com/gcushen/hugo-academic/archive/v4.8.0.zip
* Move into `themes/` directory of `exampleSite/`
* Replace [post archetype](https://github.com/gcushen/hugo-academic/blob/v4.8.0/archetypes/post/index.md) with equivalent `.Rmd`
* Create `_hugodown.yaml` with hugo_version set appropriately
* Move `config/_default/config.toml` to top level & open in RStudio. Suggest (or make?) change to `ignoreFiles`
* Open `config/_default/params.toml`
* Figure out what to do about code highlighting — want to use goldmark + donwlit, not highlight.js; https://sourcethemes.com/academic/docs/writing-markdown-latex/#code-highlighting
* Create `README.md` with basic instructions
* Provide default github action?
